### ISSUE TITLE
Request: extension of RIBLT to list intersections as well as differences

### ISSUE THREAD

**Issue by rmlearney-digicatapult** [hoytech/riblet#2]
Hello,

I'm trying to use RIBLT for something it's maybe not originally designed to do: to tell me which (if any) of Bob's keys are present in Alice's RIBLT, rather than the difference between the two sets. Perhaps more suited for a plain Bloom filter...

**Comment by hoytech** [comment]
Hi! If you have either of the sets, then you can figure out which side is missing a differing element by, trivially, checking if it already exists in the set you possess.

If you have neither of the sets and just two RIBLT streams, then I don't think there is a general way of figuring this out. You could read enough of a RIBLT stream to recover ("peel") the entire corresponding set, but that's not really the intent of the RIBLT algorithm as far as I understand it.

**Comment by rmlearney-digicatapult** [comment]
Thank you @hoytech, you're indeed right. It appears through my further reading that set reconciliation and set intersection challenges require different approaches.
